# Recorded script from Mayavi2
from numpy import array
try:
    engine = mayavi.engine
except NameError:
    from mayavi.api import Engine
    engine = Engine()
    engine.start()
if len(engine.scenes) == 0:
    engine.new_scene()
# ------------------------------------------- 
scene = engine.scenes[0]
scene.scene.do_render = True
scene.scene.do_render = True
scene.scene.do_render = True
scene.scene.do_render = True
scene.scene.do_render = True
scene.scene.do_render = True
scene.scene.do_render = True
scene.scene.do_render = True
scene.scene.do_render = True
scene.scene.do_render = True
module_manager1 = engine.scenes[1].children[0].children[0]
module_manager1.scalar_lut_manager.scalar_bar_representation.minimum_size = array([1, 1])
scene1 = engine.scenes[1]
scene1.scene.do_render = True
module_manager1.scalar_lut_manager.scalar_bar_representation.position2 = array([ 0.17,  0.8 ])
scene1.scene.do_render = True
module_manager1.scalar_lut_manager.scalar_bar_representation.position = array([ 0.82,  0.1 ])
scene1.scene.do_render = True
module_manager1.scalar_lut_manager.scalar_bar_representation.maximum_size = array([100000, 100000])
scene1.scene.do_render = True
scene1.scene.do_render = True
module_manager1.scalar_lut_manager.show_scalar_bar = True
module_manager1.scalar_lut_manager.show_legend = True
module_manager1.scalar_lut_manager.scalar_bar.height = 0.8
module_manager1.scalar_lut_manager.scalar_bar.width = 0.17
module_manager1.scalar_lut_manager.scalar_bar.position2 = array([ 0.17,  0.8 ])
module_manager1.scalar_lut_manager.scalar_bar.position = array([ 0.82,  0.1 ])
scene1.scene.do_render = True
module_manager1.scalar_lut_manager.show_scalar_bar = False
module_manager1.scalar_lut_manager.show_legend = False
module_manager = engine.scenes[0].children[0].children[0]
module_manager.scalar_lut_manager.scalar_bar_representation.minimum_size = array([1, 1])
scene.scene.do_render = True
module_manager.scalar_lut_manager.scalar_bar_representation.position2 = array([ 0.17,  0.8 ])
scene.scene.do_render = True
module_manager.scalar_lut_manager.scalar_bar_representation.position = array([ 0.82,  0.1 ])
scene.scene.do_render = True
module_manager.scalar_lut_manager.scalar_bar_representation.maximum_size = array([100000, 100000])
scene.scene.do_render = True
scene.scene.do_render = True
module_manager.scalar_lut_manager.show_scalar_bar = True
module_manager.scalar_lut_manager.show_legend = True
module_manager.scalar_lut_manager.scalar_bar.height = 0.8
module_manager.scalar_lut_manager.scalar_bar.width = 0.17
module_manager.scalar_lut_manager.scalar_bar.position2 = array([ 0.17,  0.8 ])
module_manager.scalar_lut_manager.scalar_bar.position = array([ 0.82,  0.1 ])
module_manager.scalar_lut_manager.scalar_bar.position2 = array([ 0.17,  0.8 ])
module_manager.scalar_lut_manager.scalar_bar.position = array([ 0.82,  0.1 ])
module_manager.scalar_lut_manager.scalar_bar.number_of_labels = 6
module_manager.scalar_lut_manager.scalar_bar.position2 = array([ 0.17,  0.8 ])
module_manager.scalar_lut_manager.scalar_bar.position = array([ 0.82,  0.1 ])
scene.scene.do_render = True
module_manager.scalar_lut_manager.number_of_labels = 6
module_manager.scalar_lut_manager.scalar_bar.position2 = array([ 0.17,  0.8 ])
module_manager.scalar_lut_manager.scalar_bar.position = array([ 0.82,  0.1 ])
module_manager.scalar_lut_manager.scalar_bar.number_of_labels = 0
module_manager.scalar_lut_manager.scalar_bar.position2 = array([ 0.17,  0.8 ])
module_manager.scalar_lut_manager.scalar_bar.position = array([ 0.82,  0.1 ])
scene.scene.do_render = True
module_manager.scalar_lut_manager.number_of_labels = 0
module_manager.scalar_lut_manager.scalar_bar.position2 = array([ 0.17,  0.8 ])
module_manager.scalar_lut_manager.scalar_bar.position = array([ 0.82,  0.1 ])
module_manager.scalar_lut_manager.scalar_bar.number_of_labels = 64
module_manager.scalar_lut_manager.scalar_bar.position2 = array([ 0.17,  0.8 ])
module_manager.scalar_lut_manager.scalar_bar.position = array([ 0.82,  0.1 ])
scene.scene.do_render = True
module_manager.scalar_lut_manager.number_of_labels = 64
module_manager.scalar_lut_manager.scalar_bar.position2 = array([ 0.17,  0.8 ])
module_manager.scalar_lut_manager.scalar_bar.position = array([ 0.82,  0.1 ])
module_manager.scalar_lut_manager.scalar_bar.number_of_labels = 31
module_manager.scalar_lut_manager.scalar_bar.position2 = array([ 0.17,  0.8 ])
module_manager.scalar_lut_manager.scalar_bar.position = array([ 0.82,  0.1 ])
scene.scene.do_render = True
module_manager.scalar_lut_manager.number_of_labels = 31
module_manager.scalar_lut_manager.scalar_bar.position2 = array([ 0.17,  0.8 ])
module_manager.scalar_lut_manager.scalar_bar.position = array([ 0.82,  0.1 ])
module_manager.scalar_lut_manager.scalar_bar.number_of_labels = 16
module_manager.scalar_lut_manager.scalar_bar.position2 = array([ 0.17,  0.8 ])
module_manager.scalar_lut_manager.scalar_bar.position = array([ 0.82,  0.1 ])
scene.scene.do_render = True
module_manager.scalar_lut_manager.number_of_labels = 16
module_manager.scalar_lut_manager.scalar_bar.position2 = array([ 0.17,  0.8 ])
module_manager.scalar_lut_manager.scalar_bar.position = array([ 0.82,  0.1 ])
module_manager.scalar_lut_manager.scalar_bar.number_of_labels = 9
module_manager.scalar_lut_manager.scalar_bar.position2 = array([ 0.17,  0.8 ])
module_manager.scalar_lut_manager.scalar_bar.position = array([ 0.82,  0.1 ])
scene.scene.do_render = True
module_manager.scalar_lut_manager.number_of_labels = 9
module_manager.scalar_lut_manager.scalar_bar.position2 = array([ 0.17,  0.8 ])
module_manager.scalar_lut_manager.scalar_bar.position = array([ 0.82,  0.1 ])
module_manager.scalar_lut_manager.scalar_bar.number_of_labels = 11
module_manager.scalar_lut_manager.scalar_bar.position2 = array([ 0.17,  0.8 ])
module_manager.scalar_lut_manager.scalar_bar.position = array([ 0.82,  0.1 ])
scene.scene.do_render = True
module_manager.scalar_lut_manager.number_of_labels = 11
module_manager.scalar_lut_manager.use_default_range = False
module_manager.scalar_lut_manager.scalar_bar.position2 = array([ 0.17,  0.8 ])
module_manager.scalar_lut_manager.scalar_bar.position = array([ 0.82,  0.1 ])
scene.scene.do_render = True
module_manager.scalar_lut_manager.data_range = array([ 0.62212579,  2.        ])
module_manager.scalar_lut_manager.scalar_bar.position2 = array([ 0.17,  0.8 ])
module_manager.scalar_lut_manager.scalar_bar.position = array([ 0.82,  0.1 ])
scene.scene.do_render = True
module_manager.scalar_lut_manager.data_range = array([ 0.6,  2. ])
module_manager.scalar_lut_manager.scalar_bar.position2 = array([ 0.17,  0.8 ])
module_manager.scalar_lut_manager.scalar_bar.position = array([ 0.82,  0.1 ])
module_manager.scalar_lut_manager.scalar_bar.number_of_labels = 8
module_manager.scalar_lut_manager.scalar_bar.position2 = array([ 0.17,  0.8 ])
module_manager.scalar_lut_manager.scalar_bar.position = array([ 0.82,  0.1 ])
scene.scene.do_render = True
module_manager.scalar_lut_manager.number_of_labels = 8
module_manager.scalar_lut_manager.use_default_name = False
module_manager.scalar_lut_manager.scalar_bar.position2 = array([ 0.17,  0.8 ])
module_manager.scalar_lut_manager.scalar_bar.position = array([ 0.82,  0.1 ])
module_manager.scalar_lut_manager.scalar_bar.title = 'b'
module_manager.scalar_lut_manager.scalar_bar.position2 = array([ 0.17,  0.8 ])
module_manager.scalar_lut_manager.scalar_bar.position = array([ 0.82,  0.1 ])
scene.scene.do_render = True
module_manager.scalar_lut_manager.data_name = u'b'
module_manager.scalar_lut_manager.scalar_bar.position2 = array([ 0.17,  0.8 ])
module_manager.scalar_lut_manager.scalar_bar.position = array([ 0.82,  0.1 ])
module_manager.scalar_lut_manager.scalar_bar.title = 'b-'
module_manager.scalar_lut_manager.scalar_bar.position2 = array([ 0.17,  0.8 ])
module_manager.scalar_lut_manager.scalar_bar.position = array([ 0.82,  0.1 ])
scene.scene.do_render = True
module_manager.scalar_lut_manager.data_name = u'b-'
module_manager.scalar_lut_manager.scalar_bar.position2 = array([ 0.17,  0.8 ])
module_manager.scalar_lut_manager.scalar_bar.position = array([ 0.82,  0.1 ])
module_manager.scalar_lut_manager.scalar_bar.title = 'b-v'
module_manager.scalar_lut_manager.scalar_bar.position2 = array([ 0.17,  0.8 ])
module_manager.scalar_lut_manager.scalar_bar.position = array([ 0.82,  0.1 ])
scene.scene.do_render = True
module_manager.scalar_lut_manager.data_name = u'b-v'
module_manager.scalar_lut_manager.scalar_bar.position2 = array([ 0.17,  0.8 ])
module_manager.scalar_lut_manager.scalar_bar.position = array([ 0.82,  0.1 ])
module_manager.scalar_lut_manager.scalar_bar.title = 'b-va'
module_manager.scalar_lut_manager.scalar_bar.position2 = array([ 0.17,  0.8 ])
module_manager.scalar_lut_manager.scalar_bar.position = array([ 0.82,  0.1 ])
scene.scene.do_render = True
module_manager.scalar_lut_manager.data_name = u'b-va'
module_manager.scalar_lut_manager.scalar_bar.position2 = array([ 0.17,  0.8 ])
module_manager.scalar_lut_manager.scalar_bar.position = array([ 0.82,  0.1 ])
module_manager.scalar_lut_manager.scalar_bar.title = 'b-val'
module_manager.scalar_lut_manager.scalar_bar.position2 = array([ 0.17,  0.8 ])
module_manager.scalar_lut_manager.scalar_bar.position = array([ 0.82,  0.1 ])
scene.scene.do_render = True
module_manager.scalar_lut_manager.data_name = u'b-val'
module_manager.scalar_lut_manager.scalar_bar.position2 = array([ 0.17,  0.8 ])
module_manager.scalar_lut_manager.scalar_bar.position = array([ 0.82,  0.1 ])
module_manager.scalar_lut_manager.scalar_bar.title = 'b-valu'
module_manager.scalar_lut_manager.scalar_bar.position2 = array([ 0.17,  0.8 ])
module_manager.scalar_lut_manager.scalar_bar.position = array([ 0.82,  0.1 ])
scene.scene.do_render = True
module_manager.scalar_lut_manager.data_name = u'b-valu'
module_manager.scalar_lut_manager.scalar_bar.position2 = array([ 0.17,  0.8 ])
module_manager.scalar_lut_manager.scalar_bar.position = array([ 0.82,  0.1 ])
module_manager.scalar_lut_manager.scalar_bar.title = 'b-value'
module_manager.scalar_lut_manager.scalar_bar.position2 = array([ 0.17,  0.8 ])
module_manager.scalar_lut_manager.scalar_bar.position = array([ 0.82,  0.1 ])
scene.scene.do_render = True
module_manager.scalar_lut_manager.data_name = u'b-value'
scene.scene.do_render = True
scene.scene.do_render = True
scene.scene.do_render = True
scene.scene.do_render = True
scene.scene.do_render = True
axes = engine.scenes[0].children[0].children[0].children[4]
axes.axes.render_time_multiplier = 0.8050537794555904
scene.scene.do_render = True
axes.axes.position2 = array([ 0.5,  0.5])
scene.scene.do_render = True
axes.axes.ranges = array([ 0.,  0.,  0.,  0.,  0.,  0.])
scene.scene.do_render = True
axes.axes.bounds = array([  1.,  43.,   1.,  76.,   1.,  71.])
scene.scene.do_render = True
axes.axes.position = array([ 0.,  0.])
scene.scene.do_render = True
axes.axes.number_of_labels = 7
scene.scene.do_render = True
scene.scene.do_render = True
axes.axes.position2 = array([ 0.5,  0.5])
scene.scene.do_render = True
axes.axes.ranges = array([ 0.,  0.,  0.,  0.,  0.,  0.])
scene.scene.do_render = True
axes.axes.bounds = array([  1.,  43.,   1.,  76.,   1.,  71.])
scene.scene.do_render = True
axes.axes.position = array([ 0.,  0.])
scene.scene.do_render = True
axes.axes.scaling = True
scene.scene.do_render = True
scene.scene.do_render = True
axes.axes.position2 = array([ 0.5,  0.5])
scene.scene.do_render = True
axes.axes.ranges = array([ 0.,  0.,  0.,  0.,  0.,  0.])
scene.scene.do_render = True
axes.axes.bounds = array([  1.,  43.,   1.,  76.,   1.,  71.])
scene.scene.do_render = True
axes.axes.position = array([ 0.,  0.])
scene.scene.do_render = True
axes.axes.scaling = False
scene.scene.do_render = True
scene.scene.do_render = True
axes.axes.position2 = array([ 0.5,  0.5])
scene.scene.do_render = True
axes.axes.ranges = array([ 0.,  0.,  0.,  0.,  0.,  0.])
scene.scene.do_render = True
axes.axes.bounds = array([  1.,  43.,   1.,  76.,   1.,  71.])
scene.scene.do_render = True
axes.axes.position = array([ 0.,  0.])
scene.scene.do_render = True
axes.axes.use_ranges = True
scene.scene.do_render = True
axes.axes.position2 = array([ 0.5,  0.5])
scene.scene.do_render = True
axes.axes.ranges = array([ 0.,  0.,  0.,  0.,  0.,  0.])
scene.scene.do_render = True
axes.axes.bounds = array([  1.,  43.,   1.,  76.,   1.,  71.])
scene.scene.do_render = True
axes.axes.position = array([ 0.,  0.])
scene.scene.do_render = True
axes.axes.corner_offset = 1.0
scene.scene.do_render = True
axes.axes.estimated_render_time = 1.0
scene.scene.do_render = True
axes.axes.estimated_render_time = 0.0
scene.scene.do_render = True
axes.axes.position2 = array([ 0.5,  0.5])
scene.scene.do_render = True
axes.axes.ranges = array([ 0.,  0.,  0.,  0.,  0.,  0.])
scene.scene.do_render = True
axes.axes.bounds = array([  1.,  43.,   1.,  76.,   1.,  71.])
scene.scene.do_render = True
axes.axes.position = array([ 0.,  0.])
scene.scene.do_render = True
axes.axes.corner_offset = 0.0
scene.scene.do_render = True
axes.axes.position2 = array([ 0.5,  0.5])
scene.scene.do_render = True
axes.axes.ranges = array([ 0.,  0.,  0.,  0.,  0.,  0.])
scene.scene.do_render = True
axes.axes.bounds = array([  1.,  43.,   1.,  76.,   1.,  71.])
scene.scene.do_render = True
axes.axes.position = array([ 0.,  0.])
scene.scene.do_render = True
axes.axes.label_format = '%-#6.2g'
scene.scene.do_render = True
scene.scene.do_render = True
axes.axes.position2 = array([ 0.5,  0.5])
scene.scene.do_render = True
axes.axes.ranges = array([ 0.,  0.,  0.,  0.,  0.,  0.])
scene.scene.do_render = True
axes.axes.bounds = array([  1.,  43.,   1.,  76.,   1.,  71.])
scene.scene.do_render = True
axes.axes.position = array([ 0.,  0.])
scene.scene.do_render = True
axes.axes.visibility = False
scene.scene.do_render = True
scene.scene.do_render = True
axes.axes.position2 = array([ 0.5,  0.5])
scene.scene.do_render = True
axes.axes.ranges = array([ 0.,  0.,  0.,  0.,  0.,  0.])
scene.scene.do_render = True
axes.axes.bounds = array([  1.,  43.,   1.,  76.,   1.,  71.])
scene.scene.do_render = True
axes.axes.position = array([ 0.,  0.])
scene.scene.do_render = True
axes.axes.visibility = True
scene.scene.do_render = True
scene.scene.do_render = True
axes.property.reference_count = 32
scene.scene.do_render = True
axes.property.display_location = 'background'
scene.scene.do_render = True
scene.scene.camera.position = [85.266823772369079, 144.4415185351518, 124.75642883882151]
scene.scene.camera.focal_point = [22.0, 38.5, 36.0]
scene.scene.camera.view_angle = 30.0
scene.scene.camera.view_up = [0.0, 0.0, 1.0]
scene.scene.camera.clipping_range = [38.714430249679936, 294.96982523845861]
scene.scene.camera.compute_view_plane_normal()
scene.scene.render()
axes.axes.render_time_multiplier = 0.8050537794556131
scene.scene.do_render = True
axes.axes.position2 = array([ 0.5,  0.5])
scene.scene.do_render = True
axes.axes.ranges = array([ 0.,  7.,  0.,  0.,  0.,  0.])
scene.scene.do_render = True
axes.axes.bounds = array([  1.,  43.,   1.,  76.,   1.,  71.])
scene.scene.do_render = True
axes.axes.position = array([ 0.,  0.])
scene.scene.do_render = True
axes.axes.ranges = array([ 0.,  7.,  0.,  0.,  0.,  0.])
scene.scene.do_render = True
scene.scene.camera.position = [88.632989438028588, 18.729740469868531, 171.178332422989]
scene.scene.camera.focal_point = [22.0, 38.5, 36.0]
scene.scene.camera.view_angle = 30.0
scene.scene.camera.view_up = [0.0, 0.0, 1.0]
scene.scene.camera.clipping_range = [59.061626494744743, 269.35689730182139]
scene.scene.camera.compute_view_plane_normal()
scene.scene.render()
scene.scene.camera.position = [23.174714012946133, -57.069927337108808, 154.19056238026957]
scene.scene.camera.focal_point = [22.0, 38.5, 36.0]
scene.scene.camera.view_angle = 30.0
scene.scene.camera.view_up = [0.0, 0.0, 1.0]
scene.scene.camera.clipping_range = [47.671905765573534, 283.69420907396579]
scene.scene.camera.compute_view_plane_normal()
scene.scene.render()
scene.scene.camera.position = [21.873842967457453, -12.820581822623659, 179.07404364798927]
scene.scene.camera.focal_point = [22.0, 38.5, 36.0]
scene.scene.camera.view_angle = 30.0
scene.scene.camera.view_up = [0.0, 0.0, 1.0]
scene.scene.camera.clipping_range = [58.416014213293678, 270.16959014856445]
scene.scene.camera.compute_view_plane_normal()
scene.scene.render()
scene.scene.camera.position = [23.345712695072219, -27.183127230729188, 173.0690185801659]
scene.scene.camera.focal_point = [22.0, 38.5, 36.0]
scene.scene.camera.view_angle = 30.0
scene.scene.camera.view_up = [0.0, 0.0, 1.0]
scene.scene.camera.clipping_range = [53.718320944436051, 276.08301810760003]
scene.scene.camera.compute_view_plane_normal()
scene.scene.render()
axes.axes.render_time_multiplier = 0.8050537794556655
scene.scene.do_render = True
axes.axes.position2 = array([ 0.5,  0.5])
scene.scene.do_render = True
axes.axes.ranges = array([ 178.,    7.,    0.,    0.,    0.,    0.])
scene.scene.do_render = True
axes.axes.bounds = array([  1.,  43.,   1.,  76.,   1.,  71.])
scene.scene.do_render = True
axes.axes.position = array([ 0.,  0.])
scene.scene.do_render = True
axes.axes.ranges = array([ 178.,    7.,    0.,    0.,    0.,    0.])
scene.scene.do_render = True
axes.axes.position2 = array([ 0.5,  0.5])
scene.scene.do_render = True
axes.axes.ranges = array([ 178. ,  178.5,    0. ,    0. ,    0. ,    0. ])
scene.scene.do_render = True
axes.axes.bounds = array([  1.,  43.,   1.,  76.,   1.,  71.])
scene.scene.do_render = True
axes.axes.position = array([ 0.,  0.])
scene.scene.do_render = True
axes.axes.ranges = array([ 178. ,  178.5,    0. ,    0. ,    0. ,    0. ])
scene.scene.do_render = True
axes.axes.position2 = array([ 0.5,  0.5])
scene.scene.do_render = True
axes.axes.ranges = array([ 178. ,  178.5,    0. ,    0. ,    0. ,    7. ])
scene.scene.do_render = True
axes.axes.bounds = array([  1.,  43.,   1.,  76.,   1.,  71.])
scene.scene.do_render = True
axes.axes.position = array([ 0.,  0.])
scene.scene.do_render = True
axes.axes.ranges = array([ 178. ,  178.5,    0. ,    0. ,    0. ,    7. ])
scene.scene.do_render = True
scene.scene.camera.position = [14.202327869756784, -84.924011192408813, 124.3725623172725]
scene.scene.camera.focal_point = [22.0, 38.5, 36.0]
scene.scene.camera.view_angle = 30.0
scene.scene.camera.view_up = [0.0, 0.0, 1.0]
scene.scene.camera.clipping_range = [45.808771096246971, 286.03951176071598]
scene.scene.camera.compute_view_plane_normal()
scene.scene.render()
axes.axes.render_time_multiplier = 0.8050537794556807
scene.scene.do_render = True
axes.axes.position2 = array([ 0.5,  0.5])
scene.scene.do_render = True
axes.axes.ranges = array([ 178. ,  178.5,    0. ,    0. ,    7. ,    7. ])
scene.scene.do_render = True
axes.axes.bounds = array([  1.,  43.,   1.,  76.,   1.,  71.])
scene.scene.do_render = True
axes.axes.position = array([ 0.,  0.])
scene.scene.do_render = True
axes.axes.ranges = array([ 178. ,  178.5,    0. ,    0. ,    7. ,    7. ])
scene.scene.do_render = True
axes.axes.position2 = array([ 0.5,  0.5])
scene.scene.do_render = True
axes.axes.ranges = array([ 178. ,  178.5,    0. ,    0. ,    7. ,    0. ])
scene.scene.do_render = True
axes.axes.bounds = array([  1.,  43.,   1.,  76.,   1.,  71.])
scene.scene.do_render = True
axes.axes.position = array([ 0.,  0.])
scene.scene.do_render = True
axes.axes.ranges = array([ 178. ,  178.5,    0. ,    0. ,    7. ,    0. ])
scene.scene.do_render = True
scene.scene.camera.position = [21.661129804205739, -7.4499694342986142, 180.88783757089945]
scene.scene.camera.focal_point = [22.0, 38.5, 36.0]
scene.scene.camera.view_angle = 30.0
scene.scene.camera.view_up = [0.0, 0.0, 1.0]
scene.scene.camera.clipping_range = [60.185022795067603, 267.94277281319887]
scene.scene.camera.compute_view_plane_normal()
scene.scene.render()
scene2 = engine.scenes[2]
scene2.scene.camera.position = [22.0, 38.5, 219.92000000000002]
scene2.scene.camera.focal_point = [22.0, 38.5, 36.0]
scene2.scene.camera.view_angle = 30.0
scene2.scene.camera.view_up = [0.0, 1.0, 0.0]
scene2.scene.camera.clipping_range = [112.4308, 274.35380000000004]
scene2.scene.camera.compute_view_plane_normal()
scene2.scene.render()
scene1.scene.camera.position = [22.000000000000014, 220.00000000000003, 36.000000000000007]
scene1.scene.camera.focal_point = [22.0, 38.5, 36.0]
scene1.scene.camera.view_angle = 30.0
scene1.scene.camera.view_up = [0.0, 0.0, 1.0]
scene1.scene.camera.clipping_range = [105.06000000000003, 278.16000000000003]
scene1.scene.camera.compute_view_plane_normal()
scene1.scene.render()
scene3 = engine.scenes[3]
scene3.scene.camera.position = [205.92000000000002, 38.5, 36.000000000000007]
scene3.scene.camera.focal_point = [22.0, 38.5, 36.0]
scene3.scene.camera.view_angle = 30.0
scene3.scene.camera.view_up = [0.0, 0.0, 1.0]
scene3.scene.camera.clipping_range = [140.29080000000002, 239.28380000000004]
scene3.scene.camera.compute_view_plane_normal()
scene3.scene.render()
scene.scene.do_render = True
axes.axes.render_time_multiplier = 0.8050537794556963
scene.scene.do_render = True
axes.axes.position2 = array([ 0.5,  0.5])
scene.scene.do_render = True
axes.axes.ranges = array([ 178. ,  178.5,    0. ,    0. ,    7. ,    0. ])
scene.scene.do_render = True
axes.axes.bounds = array([  1.,  43.,   1.,  76.,   1.,  71.])
scene.scene.do_render = True
axes.axes.position = array([ 0.,  0.])
scene.scene.do_render = True
axes.axes.scaling = True
scene.scene.do_render = True
image_plane_widget1 = engine.scenes[0].children[0].children[0].children[1]
image_plane_widget1.ipw.origin = array([  0.5,  35. ,   0.5])
scene.scene.do_render = True
image_plane_widget1.ipw.slice_index = 34
scene.scene.do_render = True
image_plane_widget1.ipw.point1 = array([  0.5,  35. ,  71.5])
scene.scene.do_render = True
image_plane_widget1.ipw.point2 = array([ 43.5,  35. ,   0.5])
scene.scene.do_render = True
image_plane_widget3 = engine.scenes[1].children[0].children[0].children[1]
image_plane_widget3.ipw.origin = array([  0.5,  35. ,   0.5])
scene1.scene.do_render = True
image_plane_widget3.ipw.slice_index = 34
scene1.scene.do_render = True
image_plane_widget3.ipw.point1 = array([  0.5,  35. ,  71.5])
scene1.scene.do_render = True
image_plane_widget3.ipw.point2 = array([ 43.5,  35. ,   0.5])
scene1.scene.do_render = True
image_plane_widget3.ipw.slice_position = 35.0
scene1.scene.do_render = True
image_plane_widget1.ipw.slice_position = 35.0
scene.scene.do_render = True
image_plane_widget2 = engine.scenes[0].children[0].children[0].children[2]
image_plane_widget2.ipw.origin = array([  0.5,   0.5,  36. ])
scene.scene.do_render = True
image_plane_widget2.ipw.point1 = array([ 43.5,   0.5,  36. ])
scene.scene.do_render = True
image_plane_widget2.ipw.point2 = array([  0.5,  76.5,  36. ])
scene.scene.do_render = True
image_plane_widget4 = engine.scenes[2].children[0].children[0].children[1]
image_plane_widget4.ipw.origin = array([  0.5,   0.5,  36. ])
scene2.scene.do_render = True
image_plane_widget4.ipw.point1 = array([ 43.5,   0.5,  36. ])
scene2.scene.do_render = True
image_plane_widget4.ipw.point2 = array([  0.5,  76.5,  36. ])
scene2.scene.do_render = True
image_plane_widget4.ipw.slice_position = 36.0
scene2.scene.do_render = True
image_plane_widget2.ipw.slice_position = 36.0
scene.scene.do_render = True
image_plane_widget5 = engine.scenes[3].children[0].children[0].children[1]
image_plane_widget5.ipw.origin = array([ 21.5,   0.5,   0.5])
scene3.scene.do_render = True
image_plane_widget5.ipw.point1 = array([ 21.5,  76.5,   0.5])
scene3.scene.do_render = True
image_plane_widget5.ipw.point2 = array([ 21.5,   0.5,  71.5])
scene3.scene.do_render = True
image_plane_widget5.ipw.origin = array([ 21.5,   0.5,   0.5])
scene3.scene.do_render = True
image_plane_widget5.ipw.point1 = array([ 21.5,  76.5,   0.5])
scene3.scene.do_render = True
image_plane_widget5.ipw.point2 = array([ 21.5,   0.5,  71.5])
scene3.scene.do_render = True
image_plane_widget1.ipw.origin = array([  0.5,  41. ,   0.5])
scene.scene.do_render = True
image_plane_widget1.ipw.slice_index = 40
scene.scene.do_render = True
image_plane_widget1.ipw.point1 = array([  0.5,  41. ,  71.5])
scene.scene.do_render = True
image_plane_widget1.ipw.point2 = array([ 43.5,  41. ,   0.5])
scene.scene.do_render = True
image_plane_widget3.ipw.origin = array([  0.5,  41. ,   0.5])
scene1.scene.do_render = True
image_plane_widget3.ipw.slice_index = 40
scene1.scene.do_render = True
image_plane_widget3.ipw.point1 = array([  0.5,  41. ,  71.5])
scene1.scene.do_render = True
image_plane_widget3.ipw.point2 = array([ 43.5,  41. ,   0.5])
scene1.scene.do_render = True
image_plane_widget3.ipw.slice_position = 41.0
scene1.scene.do_render = True
image_plane_widget1.ipw.slice_position = 41.0
scene.scene.do_render = True
image_plane_widget2.ipw.origin = array([  0.5,   0.5,  39. ])
scene.scene.do_render = True
image_plane_widget2.ipw.slice_index = 38
scene.scene.do_render = True
image_plane_widget2.ipw.point1 = array([ 43.5,   0.5,  39. ])
scene.scene.do_render = True
image_plane_widget2.ipw.point2 = array([  0.5,  76.5,  39. ])
scene.scene.do_render = True
image_plane_widget4.ipw.origin = array([  0.5,   0.5,  39. ])
scene2.scene.do_render = True
image_plane_widget4.ipw.slice_index = 38
scene2.scene.do_render = True
image_plane_widget4.ipw.point1 = array([ 43.5,   0.5,  39. ])
scene2.scene.do_render = True
image_plane_widget4.ipw.point2 = array([  0.5,  76.5,  39. ])
scene2.scene.do_render = True
image_plane_widget4.ipw.slice_position = 39.0
scene2.scene.do_render = True
image_plane_widget2.ipw.slice_position = 39.0
scene.scene.do_render = True
image_plane_widget1.ipw.origin = array([  0.5,  37. ,   0.5])
scene.scene.do_render = True
image_plane_widget1.ipw.slice_index = 36
scene.scene.do_render = True
image_plane_widget1.ipw.point1 = array([  0.5,  37. ,  71.5])
scene.scene.do_render = True
image_plane_widget1.ipw.point2 = array([ 43.5,  37. ,   0.5])
scene.scene.do_render = True
image_plane_widget3.ipw.origin = array([  0.5,  37. ,   0.5])
scene1.scene.do_render = True
image_plane_widget3.ipw.slice_index = 36
scene1.scene.do_render = True
image_plane_widget3.ipw.point1 = array([  0.5,  37. ,  71.5])
scene1.scene.do_render = True
image_plane_widget3.ipw.point2 = array([ 43.5,  37. ,   0.5])
scene1.scene.do_render = True
image_plane_widget3.ipw.slice_position = 37.0
scene1.scene.do_render = True
image_plane_widget1.ipw.slice_position = 37.0
scene.scene.do_render = True
image_plane_widget2.ipw.origin = array([  0.5,   0.5,  53. ])
scene.scene.do_render = True
image_plane_widget2.ipw.slice_index = 52
scene.scene.do_render = True
image_plane_widget2.ipw.point1 = array([ 43.5,   0.5,  53. ])
scene.scene.do_render = True
image_plane_widget2.ipw.point2 = array([  0.5,  76.5,  53. ])
scene.scene.do_render = True
image_plane_widget4.ipw.origin = array([  0.5,   0.5,  53. ])
scene2.scene.do_render = True
image_plane_widget4.ipw.slice_index = 52
scene2.scene.do_render = True
image_plane_widget4.ipw.point1 = array([ 43.5,   0.5,  53. ])
scene2.scene.do_render = True
image_plane_widget4.ipw.point2 = array([  0.5,  76.5,  53. ])
scene2.scene.do_render = True
image_plane_widget4.ipw.slice_position = 53.0
scene2.scene.do_render = True
image_plane_widget2.ipw.slice_position = 53.0
scene.scene.do_render = True
image_plane_widget5.ipw.origin = array([ 21.5,   0.5,   0.5])
scene3.scene.do_render = True
image_plane_widget5.ipw.point1 = array([ 21.5,  76.5,   0.5])
scene3.scene.do_render = True
image_plane_widget5.ipw.point2 = array([ 21.5,   0.5,  71.5])
scene3.scene.do_render = True
image_plane_widget5.ipw.origin = array([ 21.5,   0.5,   0.5])
scene3.scene.do_render = True
image_plane_widget5.ipw.point1 = array([ 21.5,  76.5,   0.5])
scene3.scene.do_render = True
image_plane_widget5.ipw.point2 = array([ 21.5,   0.5,  71.5])
scene3.scene.do_render = True
image_plane_widget2.ipw.origin = array([  0.5,   0.5,  55. ])
scene.scene.do_render = True
image_plane_widget2.ipw.slice_index = 54
scene.scene.do_render = True
image_plane_widget2.ipw.point1 = array([ 43.5,   0.5,  55. ])
scene.scene.do_render = True
image_plane_widget2.ipw.point2 = array([  0.5,  76.5,  55. ])
scene.scene.do_render = True
image_plane_widget4.ipw.origin = array([  0.5,   0.5,  55. ])
scene2.scene.do_render = True
image_plane_widget4.ipw.slice_index = 54
scene2.scene.do_render = True
image_plane_widget4.ipw.point1 = array([ 43.5,   0.5,  55. ])
scene2.scene.do_render = True
image_plane_widget4.ipw.point2 = array([  0.5,  76.5,  55. ])
scene2.scene.do_render = True
image_plane_widget4.ipw.slice_position = 55.0
scene2.scene.do_render = True
image_plane_widget2.ipw.slice_position = 55.0
scene.scene.do_render = True
image_plane_widget1.ipw.origin = array([  0.5,  36. ,   0.5])
scene.scene.do_render = True
image_plane_widget1.ipw.slice_index = 35
scene.scene.do_render = True
image_plane_widget1.ipw.point1 = array([  0.5,  36. ,  71.5])
scene.scene.do_render = True
image_plane_widget1.ipw.point2 = array([ 43.5,  36. ,   0.5])
scene.scene.do_render = True
image_plane_widget3.ipw.origin = array([  0.5,  36. ,   0.5])
scene1.scene.do_render = True
image_plane_widget3.ipw.slice_index = 35
scene1.scene.do_render = True
image_plane_widget3.ipw.point1 = array([  0.5,  36. ,  71.5])
scene1.scene.do_render = True
image_plane_widget3.ipw.point2 = array([ 43.5,  36. ,   0.5])
scene1.scene.do_render = True
image_plane_widget3.ipw.slice_position = 36.0
scene1.scene.do_render = True
image_plane_widget1.ipw.slice_position = 36.0
scene.scene.do_render = True
image_plane_widget2.ipw.origin = array([  0.5,   0.5,  42. ])
scene.scene.do_render = True
image_plane_widget2.ipw.slice_index = 41
scene.scene.do_render = True
image_plane_widget2.ipw.point1 = array([ 43.5,   0.5,  42. ])
scene.scene.do_render = True
image_plane_widget2.ipw.point2 = array([  0.5,  76.5,  42. ])
scene.scene.do_render = True
image_plane_widget4.ipw.origin = array([  0.5,   0.5,  42. ])
scene2.scene.do_render = True
image_plane_widget4.ipw.slice_index = 41
scene2.scene.do_render = True
image_plane_widget4.ipw.point1 = array([ 43.5,   0.5,  42. ])
scene2.scene.do_render = True
image_plane_widget4.ipw.point2 = array([  0.5,  76.5,  42. ])
scene2.scene.do_render = True
image_plane_widget4.ipw.slice_position = 42.0
scene2.scene.do_render = True
image_plane_widget2.ipw.slice_position = 42.0
scene.scene.do_render = True
image_plane_widget5.ipw.origin = array([ 21.5,   0.5,   0.5])
scene3.scene.do_render = True
image_plane_widget5.ipw.point1 = array([ 21.5,  76.5,   0.5])
scene3.scene.do_render = True
image_plane_widget5.ipw.point2 = array([ 21.5,   0.5,  71.5])
scene3.scene.do_render = True
image_plane_widget5.ipw.origin = array([ 21.5,   0.5,   0.5])
scene3.scene.do_render = True
image_plane_widget5.ipw.point1 = array([ 21.5,  76.5,   0.5])
scene3.scene.do_render = True
image_plane_widget5.ipw.point2 = array([ 21.5,   0.5,  71.5])
scene3.scene.do_render = True
scene.scene.camera.position = [93.178942353251628, -75.951979214353486, 106.27305756393126]
scene.scene.camera.focal_point = [22.0, 38.5, 36.0]
scene.scene.camera.view_angle = 30.0
scene.scene.camera.view_up = [0.0, 0.0, 1.0]
scene.scene.camera.clipping_range = [40.843882444852554, 292.28928365605736]
scene.scene.camera.compute_view_plane_normal()
scene.scene.render()
scene.scene.camera.position = [-39.139795908364249, -57.68752477644356, 136.56781509836171]
scene.scene.camera.focal_point = [22.0, 38.5, 36.0]
scene.scene.camera.view_angle = 30.0
scene.scene.camera.view_up = [0.0, 0.0, 1.0]
scene.scene.camera.clipping_range = [38.676183623925859, 295.01796986028728]
scene.scene.camera.compute_view_plane_normal()
scene.scene.render()
image_plane_widget1.ipw.origin = array([  0.5,  59. ,   0.5])
scene.scene.do_render = True
image_plane_widget1.ipw.slice_index = 58
scene.scene.do_render = True
image_plane_widget1.ipw.point1 = array([  0.5,  59. ,  71.5])
scene.scene.do_render = True
image_plane_widget1.ipw.point2 = array([ 43.5,  59. ,   0.5])
scene.scene.do_render = True
image_plane_widget3.ipw.origin = array([  0.5,  59. ,   0.5])
scene1.scene.do_render = True
image_plane_widget3.ipw.slice_index = 58
scene1.scene.do_render = True
image_plane_widget3.ipw.point1 = array([  0.5,  59. ,  71.5])
scene1.scene.do_render = True
image_plane_widget3.ipw.point2 = array([ 43.5,  59. ,   0.5])
scene1.scene.do_render = True
image_plane_widget3.ipw.slice_position = 59.0
scene1.scene.do_render = True
image_plane_widget1.ipw.slice_position = 59.0
scene.scene.do_render = True
image_plane_widget = engine.scenes[0].children[0].children[0].children[0]
image_plane_widget.ipw.origin = array([ 16. ,   0.5,   0.5])
scene.scene.do_render = True
image_plane_widget.ipw.slice_index = 15
scene.scene.do_render = True
image_plane_widget.ipw.point1 = array([ 16. ,  76.5,   0.5])
scene.scene.do_render = True
image_plane_widget.ipw.point2 = array([ 16. ,   0.5,  71.5])
scene.scene.do_render = True
image_plane_widget5.ipw.origin = array([ 16. ,   0.5,   0.5])
scene3.scene.do_render = True
image_plane_widget5.ipw.slice_index = 15
scene3.scene.do_render = True
image_plane_widget5.ipw.point1 = array([ 16. ,  76.5,   0.5])
scene3.scene.do_render = True
image_plane_widget5.ipw.point2 = array([ 16. ,   0.5,  71.5])
scene3.scene.do_render = True
image_plane_widget5.ipw.slice_position = 16.0
scene3.scene.do_render = True
image_plane_widget.ipw.slice_position = 16.0
scene.scene.do_render = True
image_plane_widget4.ipw.origin = array([  0.5,   0.5,  42. ])
scene2.scene.do_render = True
image_plane_widget4.ipw.point1 = array([ 43.5,   0.5,  42. ])
scene2.scene.do_render = True
image_plane_widget4.ipw.point2 = array([  0.5,  76.5,  42. ])
scene2.scene.do_render = True
image_plane_widget4.ipw.origin = array([  0.5,   0.5,  42. ])
scene2.scene.do_render = True
image_plane_widget4.ipw.point1 = array([ 43.5,   0.5,  42. ])
scene2.scene.do_render = True
image_plane_widget4.ipw.point2 = array([  0.5,  76.5,  42. ])
scene2.scene.do_render = True
scene.scene.camera.position = [73.259821496513325, -80.333623349632802, 115.71825801995953]
scene.scene.camera.focal_point = [22.0, 38.5, 36.0]
scene.scene.camera.view_angle = 30.0
scene.scene.camera.view_up = [0.0, 0.0, 1.0]
scene.scene.camera.clipping_range = [39.881010537808862, 293.50134100637939]
scene.scene.camera.compute_view_plane_normal()
scene.scene.render()
image_plane_widget2.ipw.origin = array([  0.5,   0.5,  63. ])
scene.scene.do_render = True
image_plane_widget2.ipw.slice_index = 62
scene.scene.do_render = True
image_plane_widget2.ipw.point1 = array([ 43.5,   0.5,  63. ])
scene.scene.do_render = True
image_plane_widget2.ipw.point2 = array([  0.5,  76.5,  63. ])
scene.scene.do_render = True
image_plane_widget4.ipw.origin = array([  0.5,   0.5,  63. ])
scene2.scene.do_render = True
image_plane_widget4.ipw.slice_index = 62
scene2.scene.do_render = True
image_plane_widget4.ipw.point1 = array([ 43.5,   0.5,  63. ])
scene2.scene.do_render = True
image_plane_widget4.ipw.point2 = array([  0.5,  76.5,  63. ])
scene2.scene.do_render = True
image_plane_widget4.ipw.slice_position = 63.0
scene2.scene.do_render = True
image_plane_widget2.ipw.slice_position = 63.0
scene.scene.do_render = True
image_plane_widget.ipw.origin = array([ 14. ,   0.5,   0.5])
scene.scene.do_render = True
image_plane_widget.ipw.slice_index = 13
scene.scene.do_render = True
image_plane_widget.ipw.point1 = array([ 14. ,  76.5,   0.5])
scene.scene.do_render = True
image_plane_widget.ipw.point2 = array([ 14. ,   0.5,  71.5])
scene.scene.do_render = True
image_plane_widget5.ipw.origin = array([ 14. ,   0.5,   0.5])
scene3.scene.do_render = True
image_plane_widget5.ipw.slice_index = 13
scene3.scene.do_render = True
image_plane_widget5.ipw.point1 = array([ 14. ,  76.5,   0.5])
scene3.scene.do_render = True
image_plane_widget5.ipw.point2 = array([ 14. ,   0.5,  71.5])
scene3.scene.do_render = True
image_plane_widget5.ipw.slice_position = 14.0
scene3.scene.do_render = True
image_plane_widget.ipw.slice_position = 14.0
scene.scene.do_render = True
image_plane_widget2.ipw.origin = array([  0.5,   0.5,  54. ])
scene.scene.do_render = True
image_plane_widget2.ipw.slice_index = 53
scene.scene.do_render = True
image_plane_widget2.ipw.point1 = array([ 43.5,   0.5,  54. ])
scene.scene.do_render = True
image_plane_widget2.ipw.point2 = array([  0.5,  76.5,  54. ])
scene.scene.do_render = True
image_plane_widget4.ipw.origin = array([  0.5,   0.5,  54. ])
scene2.scene.do_render = True
image_plane_widget4.ipw.slice_index = 53
scene2.scene.do_render = True
image_plane_widget4.ipw.point1 = array([ 43.5,   0.5,  54. ])
scene2.scene.do_render = True
image_plane_widget4.ipw.point2 = array([  0.5,  76.5,  54. ])
scene2.scene.do_render = True
image_plane_widget4.ipw.slice_position = 54.0
scene2.scene.do_render = True
image_plane_widget2.ipw.slice_position = 54.0
scene.scene.do_render = True
image_plane_widget3.ipw.origin = array([  0.5,  59. ,   0.5])
scene1.scene.do_render = True
image_plane_widget3.ipw.point1 = array([  0.5,  59. ,  71.5])
scene1.scene.do_render = True
image_plane_widget3.ipw.point2 = array([ 43.5,  59. ,   0.5])
scene1.scene.do_render = True
image_plane_widget3.ipw.origin = array([  0.5,  59. ,   0.5])
scene1.scene.do_render = True
image_plane_widget3.ipw.point1 = array([  0.5,  59. ,  71.5])
scene1.scene.do_render = True
image_plane_widget3.ipw.point2 = array([ 43.5,  59. ,   0.5])
scene1.scene.do_render = True
image_plane_widget1.ipw.origin = array([  0.5,  47. ,   0.5])
scene.scene.do_render = True
image_plane_widget1.ipw.slice_index = 46
scene.scene.do_render = True
image_plane_widget1.ipw.point1 = array([  0.5,  47. ,  71.5])
scene.scene.do_render = True
image_plane_widget1.ipw.point2 = array([ 43.5,  47. ,   0.5])
scene.scene.do_render = True
image_plane_widget3.ipw.origin = array([  0.5,  47. ,   0.5])
scene1.scene.do_render = True
image_plane_widget3.ipw.slice_index = 46
scene1.scene.do_render = True
image_plane_widget3.ipw.point1 = array([  0.5,  47. ,  71.5])
scene1.scene.do_render = True
image_plane_widget3.ipw.point2 = array([ 43.5,  47. ,   0.5])
scene1.scene.do_render = True
image_plane_widget3.ipw.slice_position = 47.0
scene1.scene.do_render = True
image_plane_widget1.ipw.slice_position = 47.0
scene.scene.do_render = True
image_plane_widget2.ipw.origin = array([  0.5,   0.5,  51. ])
scene.scene.do_render = True
image_plane_widget2.ipw.slice_index = 50
scene.scene.do_render = True
image_plane_widget2.ipw.point1 = array([ 43.5,   0.5,  51. ])
scene.scene.do_render = True
image_plane_widget2.ipw.point2 = array([  0.5,  76.5,  51. ])
scene.scene.do_render = True
image_plane_widget4.ipw.origin = array([  0.5,   0.5,  51. ])
scene2.scene.do_render = True
image_plane_widget4.ipw.slice_index = 50
scene2.scene.do_render = True
image_plane_widget4.ipw.point1 = array([ 43.5,   0.5,  51. ])
scene2.scene.do_render = True
image_plane_widget4.ipw.point2 = array([  0.5,  76.5,  51. ])
scene2.scene.do_render = True
image_plane_widget4.ipw.slice_position = 51.0
scene2.scene.do_render = True
image_plane_widget2.ipw.slice_position = 51.0
scene.scene.do_render = True
image_plane_widget1.ipw.origin = array([  0.5,  45. ,   0.5])
scene.scene.do_render = True
image_plane_widget1.ipw.slice_index = 44
scene.scene.do_render = True
image_plane_widget1.ipw.point1 = array([  0.5,  45. ,  71.5])
scene.scene.do_render = True
image_plane_widget1.ipw.point2 = array([ 43.5,  45. ,   0.5])
scene.scene.do_render = True
image_plane_widget3.ipw.origin = array([  0.5,  45. ,   0.5])
scene1.scene.do_render = True
image_plane_widget3.ipw.slice_index = 44
scene1.scene.do_render = True
image_plane_widget3.ipw.point1 = array([  0.5,  45. ,  71.5])
scene1.scene.do_render = True
image_plane_widget3.ipw.point2 = array([ 43.5,  45. ,   0.5])
scene1.scene.do_render = True
image_plane_widget3.ipw.slice_position = 45.0
scene1.scene.do_render = True
image_plane_widget1.ipw.slice_position = 45.0
scene.scene.do_render = True
image_plane_widget2.ipw.origin = array([  0.5,   0.5,  43. ])
scene.scene.do_render = True
image_plane_widget2.ipw.slice_index = 42
scene.scene.do_render = True
image_plane_widget2.ipw.point1 = array([ 43.5,   0.5,  43. ])
scene.scene.do_render = True
image_plane_widget2.ipw.point2 = array([  0.5,  76.5,  43. ])
scene.scene.do_render = True
image_plane_widget4.ipw.origin = array([  0.5,   0.5,  43. ])
scene2.scene.do_render = True
image_plane_widget4.ipw.slice_index = 42
scene2.scene.do_render = True
image_plane_widget4.ipw.point1 = array([ 43.5,   0.5,  43. ])
scene2.scene.do_render = True
image_plane_widget4.ipw.point2 = array([  0.5,  76.5,  43. ])
scene2.scene.do_render = True
image_plane_widget4.ipw.slice_position = 43.0
scene2.scene.do_render = True
image_plane_widget2.ipw.slice_position = 43.0
scene.scene.do_render = True
image_plane_widget5.ipw.origin = array([ 14. ,   0.5,   0.5])
scene3.scene.do_render = True
image_plane_widget5.ipw.point1 = array([ 14. ,  76.5,   0.5])
scene3.scene.do_render = True
image_plane_widget5.ipw.point2 = array([ 14. ,   0.5,  71.5])
scene3.scene.do_render = True
image_plane_widget5.ipw.origin = array([ 14. ,   0.5,   0.5])
scene3.scene.do_render = True
image_plane_widget5.ipw.point1 = array([ 14. ,  76.5,   0.5])
scene3.scene.do_render = True
image_plane_widget5.ipw.point2 = array([ 14. ,   0.5,  71.5])
scene3.scene.do_render = True
